language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - os: linux
    python: 3.6
  - os: linux
    python: 3.5
  - os: linux
    python: 2.7
  - name: "PyPy: 3.5"
    os: linux
    env: PYPY_URL=https://bitbucket.org/pypy/pypy/downloads/pypy3-v6.0.0-linux64.tar.bz2
  - name: "PyPy: 2.7"
    os: linux
    env: PYPY_URL=https://bitbucket.org/pypy/pypy/downloads/pypy2-v6.0.0-linux64.tar.bz2
  # Travis Python images not working properly with OSX - see https://github.com/travis-ci/travis-ci/issues/9744.
  # Have to rely on pyenv.
  - name: "Python: 3.7 OSX"
    os: osx
    language: generic
    env: PYENV_VERSION=3.7.0
    osx_image: xcode_9.4
  - name: "Python: 3.6 OSX"
    os: osx
    language: generic
    env: PYENV_VERSION=3.6.5
    osx_image: xcode_9.4
  - name: "Python: 2.7 OSX"
    os: osx
    language: generic
    env: PYENV_VERSION=2.7.15
    osx_image: xcode_9.4
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  provider: releases
  api_key:
    secure: Z5m7K1UVq0812nNtR+QAkUE3lxUwhMjM3EDWUOyPmfh0rmOsU2RgQ8oBfT1vatYfY8ExnrG4rRNWmwUqPEIzZmRLmw9zv+ixA3gcVPn6WbbMkwoeIurOPsC9wjgCckDFKYhMda8a92FSL2hVto3JPcRNTZnsKBR35Queray55SM=
  file:
    - dist/*.whl
    - dist/*.tar.gz
  file_glob: true
  on:
    repo: xattr/xattr
    tags: true
  skip_cleanup: true
