language: python
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
matrix:
  include:
  - os: osx
    language: objective-c
    env: BUILD_SDIST=true
  - os: osx
    language: objective-c
    env: PYENV_VERSION=pypy3.5-5.10.0
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.14
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.4
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.6.4
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
deploy:
  provider: releases
  api_key:
    secure: Z5m7K1UVq0812nNtR+QAkUE3lxUwhMjM3EDWUOyPmfh0rmOsU2RgQ8oBfT1vatYfY8ExnrG4rRNWmwUqPEIzZmRLmw9zv+ixA3gcVPn6WbbMkwoeIurOPsC9wjgCckDFKYhMda8a92FSL2hVto3JPcRNTZnsKBR35Queray55SM=
  file:
    - dist/*.whl
    - dist/*.tar.gz
  file_glob: true
  on:
    repo: xattr/xattr
    tags: true
  skip_cleanup: true
